### ISSUE TITLE
Update vector docs when vector 0.37 released

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/docs#852]
In next version of vector, we will have TLS support for greptimedb sink. It will be required for cloud users to enable TLS and use secure port via:

```toml
[sinks.my_sink_id]
inputs = ["my-source-or-transform-id"]
type = "greptimedb"
endpoint = "<host>:5001"
dbname = "<dbname>"
username = "<username>"
password = "<password>"
tls = {}
```

Open-source users will keep using plain-text port 4001, with original configuration, because grpc over tls is not implemented yet.
